import { useState } from 'react'
import { createRoot } from 'react-dom/client'
import type { ArchiveCoverage, Collection, StorageRoot, StorageRootObservation, WorkspaceTab } from '../../shared/contracts/truth-kernel'
import { CatalogNavigator, CatalogOnboarding, RootSettingsList, type CatalogSidebarMode } from './components/catalog/CatalogNavigator'
import { createCatalogOnboardingPreview, type CatalogOnboardingArchiveChoice } from '../../shared/catalog-onboarding-preview'
import { WorkspaceTabs } from './components/workspace-tabs/WorkspaceTabs'
import './catalog-visual.css'
import './catalog-visual-overrides.css'

const none = { status: 'unavailable', reason: 'fixture' } as const
const scope = { logicalSessionIds: [], rootIds: [], collectionIds: [], providerIds: [], projectIds: [], pathPrefixes: [], timeRange: none, textQuery: none, emptyFilterSemantics: 'all-catalog' as const }
const tab = (id: string, title: string, pinned = false): WorkspaceTab => ({ schemaVersion: 1, tabId: id, title, scope, view: 'sessions', sidebarMode: 'collections', selectedObjectId: none, filters: {}, sort: none, navigationHistory: [], scrollState: { anchorObjectId: none, offsetPx: 0 }, layoutState: { density: 'comfortable', inspectorOpen: false, splitRatio: none }, pinned, persisted: true })
const roots: Array<{ root: StorageRoot; observation: StorageRootObservation }> = [
  { root: { schemaVersion: 1, rootId: 'library', displayName: 'Default Swob Library with a deliberately long local path', kind: 'managed-library', capability: 'read-only', layoutPolicy: 'loose-root', includeRules: [], excludeRules: [], isDefaultArchiveTarget: false }, observation: { schemaVersion: 1, observationId: 'online', rootId: 'library', deviceId: 'fixture', permissionState: 'granted', availabilityState: 'online', scanState: 'fresh', lastSeenAt: { status: 'available', value: '2026-08-11T00:00:00Z' }, lastSuccessfulScanAt: { status: 'available', value: '2026-08-11T00:00:00Z' }, failureCode: none, observedAt: '2026-08-11T00:00:00Z' } },
  { root: { schemaVersion: 1, rootId: 'vault', displayName: 'Obsidian Vault / Projects / Very long nested session package directory', kind: 'obsidian-vault', capability: 'read-only', layoutPolicy: 'preserve-user-layout', includeRules: [], excludeRules: [], isDefaultArchiveTarget: false }, observation: { schemaVersion: 1, observationId: 'offline', rootId: 'vault', deviceId: 'fixture', permissionState: 'granted', availabilityState: 'offline', scanState: 'stale', lastSeenAt: { status: 'available', value: '2026-08-10T00:00:00Z' }, lastSuccessfulScanAt: { status: 'available', value: '2026-08-10T00:00:00Z' }, failureCode: { status: 'available', value: 'ENODEV' }, observedAt: '2026-08-11T00:00:00Z' } },
  { root: { schemaVersion: 1, rootId: 'external', displayName: 'External project folder', kind: 'external-folder', capability: 'read-only', layoutPolicy: 'preserve-user-layout', includeRules: [], excludeRules: [], isDefaultArchiveTarget: false }, observation: { schemaVersion: 1, observationId: 'denied', rootId: 'external', deviceId: 'fixture', permissionState: 'denied', availabilityState: 'unavailable', scanState: 'failed', lastSeenAt: none, lastSuccessfulScanAt: none, failureCode: { status: 'available', value: 'EACCES' }, observedAt: '2026-08-11T00:00:00Z' } }
]
const collections: Collection[] = ['Swob · 2026 launch with a very long project name', 'Favorites', 'Team context'].map((name, index) => ({ schemaVersion: 1, collectionId: `collection-${index}`, name, kind: index === 0 ? 'project' : 'manual', scope: none }))
const coverage: ArchiveCoverage = { schemaVersion: 1, knownLogicalSessions: 1842, archivedLogicalSessions: 1610, sourceOnlyLogicalSessions: 212, offlineLogicalSessions: 8, conflictedLogicalSessions: 12, unavailableLogicalSessions: 10, logicalSessionIds: [], packageIds: [], offlineRootIds: ['vault'], unavailableRootIds: ['external'], scope, scopeFingerprint: 'fixture', responseGeneration: '1', computedAt: '2026-08-11T00:00:00Z' }
const onboardingPreview = createCatalogOnboardingPreview({ previewId: 'visual-fixture-derived-preview', sessionCount: 1842, estimatedArchiveBytes: 734003200, privacyScopes: ['provider:claude-code', 'root:obsidian-vault:vault'], sourceCount: 2, complete: true })

function Fixture() {
  const locale = new URLSearchParams(window.location.search).get('locale') === 'zh' ? 'zh' : 'en'
  document.documentElement.dataset.theme = new URLSearchParams(window.location.search).get('theme') || 'dark'
  const [tabs, setTabs] = useState([tab('all', 'All sessions · Insights', true), tab('vault', 'Obsidian Vault · Sessions'), tab('source', 'Claude Code · Token'), tab('collection', 'Swob project · Chronicle'), tab('offline', 'Offline Vault · Sessions'), tab('context', 'Context Pack · Preview')])
  const [closed, setClosed] = useState<WorkspaceTab[]>([]); const [active, setActive] = useState('all'); const [mode, setMode] = useState<CatalogSidebarMode>('collections'); const [scopeLabel, setScopeLabel] = useState('All catalog'); const [sidebarWidth, setSidebarWidth] = useState(260); const [choice, setChoice] = useState<CatalogOnboardingArchiveChoice>()
  const close = (id: string) => { setTabs((value) => { const target = value.find((item) => item.tabId === id); if (target) setClosed((items) => [target, ...items]); return value.filter((item) => item.tabId !== id) }) }
  const startResize = (event: React.MouseEvent) => { event.preventDefault(); const move = (moveEvent: MouseEvent) => setSidebarWidth(Math.max(180, Math.min(420, moveEvent.clientX))); const stop = () => { window.removeEventListener('mousemove', move); window.removeEventListener('mouseup', stop) }; window.addEventListener('mousemove', move); window.addEventListener('mouseup', stop) }
  return <main><WorkspaceTabs tabs={tabs} activeTabId={active} onActivate={setActive} onClose={close} onCreate={() => setTabs((value) => [...value, tab(`new-${value.length}`, 'New scope')])} onPin={(id, pinned) => setTabs((value) => value.map((item) => item.tabId === id ? { ...item, pinned } : item))} onDuplicate={(id) => setTabs((value) => { const source = value.find((item) => item.tabId === id)!; return [...value, { ...source, tabId: `${id}-copy`, title: `${source.title} copy`, pinned: false }] })} onRename={(id) => setTabs((value) => value.map((item) => item.tabId === id ? { ...item, title: `${item.title} renamed` } : item))} onRestoreRecentlyClosed={() => { const target = closed[0]; if (target) { setTabs((value) => [...value, target]); setClosed((value) => value.slice(1)) } }} locale={locale} />
    <div className="fixture-shell" style={{ gridTemplateColumns: `${sidebarWidth}px 5px minmax(300px,1fr)` }}><CatalogNavigator mode={mode} onModeChange={setMode} collections={collections} roots={roots} sources={[{ id: 'claude', label: 'Claude Code', count: 803 }, { id: 'codex', label: 'Codex', count: 438 }]} coverage={coverage} onScope={setScopeLabel} onCoverageDrillDown={(state) => setScopeLabel(`coverage:${state}`)} locale={locale} />
      <div className="sidebar-resizer" role="separator" aria-label="Resize Catalog sidebar" aria-orientation="vertical" onMouseDown={startResize} />
      <article><h1>Read-only Device Catalog</h1><p>Current scope: <strong>{scopeLabel}</strong></p><p className="long-copy">No packages are moved, copied, deleted, or written by this fixture. Horizontal and vertical overflow is intentionally available for inspection.</p><CatalogOnboarding preview={onboardingPreview} choice={choice} onChoice={setChoice} locale={locale} /><RootSettingsList roots={roots} onAdd={() => setScopeLabel('add-root')} onRemove={(id) => setScopeLabel(`remove:${id}`)} onRescan={(id) => setScopeLabel(`rescan:${id}`)} locale={locale} /></article></div></main>
}
createRoot(document.getElementById('root')!).render(<Fixture />)
